<?php

namespace Meupf\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function myFindAll(){
        $queryBuilder = $this->createNativeNamedQuery('u');
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;
    }

    public function getUsers($page, $nbPerPage){
        $query = $this->createQueryBuilder('u')->getQuery();

        $query ->setFirstResult(($page-1) * $nbPerPage)
               ->setMaxResults($nbPerPage);

        return new Paginator($query, true);
    }
}
