security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Meupf\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
          - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/plateform/resetting, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN] }
          - { path: ^/plateform/article, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN] }
          - { path: ^/plateform/dashboard, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN] }
          - { path: ^/plateform/categorie, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN] }
          - { path: ^/plateform/sermon, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN] }
          - { path: ^/plateform/service, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN] }
          - { path: ^/plateform/event, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN] }
          - { path: ^/plateform/user, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_AUTEUR] }
          - { path: ^/plateform/register, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN] }
          - { path: ^/plateform/profile, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN] }


    providers:
        fos_userbundle:
            id: fos_user.user_manager
        main:
          id: fos_user.user_provider.username

    firewalls:
        main_login:
            pattern: ^/login$
            anonymous: true #on autorise les users anonyme sur le pare-feu
        main:
         pattern: ^/
         anonymous: true
         provider: main


         form_login:
             login_path: fos_user_security_login
             check_path: fos_user_security_check
             always_use_default_target_path : true
             provider: fos_userbundle
             default_target_path: /plateform/dashboard
             use_referer : true
         logout:
             path: fos_user_security_logout
             target: /plateform/login # / selon le tuto et pas login
         remember_me:
             key:      %secret%



    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

