# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]



    meupf_user.registration.form.type:
           class: Meupf\UserBundle\Form\Type\RegistrationFormType
           arguments: [%fos_user.model.user.class%]
           tags:
               - { name: form.type, alias: meupf_user_registration }


