<?php

namespace Meupf\PlateformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieArticleRepository extends EntityRepository
{
    public function myFindAll(){
        // Méthode 1 : en passant par l'EntityManager
        $queryBuilder = $this->createNativeNamedQuery('c');
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;
    }

    public function getCategories($page, $nbPerPage){
        $query = $this->createQueryBuilder('c')->getQuery();
        $query ->setFirstResult(($page-1) * $nbPerPage)->setMaxResults($nbPerPage);
        return new Paginator($query, true);
    }

    public function getCategorieArticle($nbPerPage){
        $queryBuilder = $this->createQueryBuilder('c');
        $query = $queryBuilder->getQuery();
        $query->setMaxResults($nbPerPage);
        $result = $query->getResult();
        return $result;
    }

}
