<?php

namespace Meupf\PlateformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function myFindAll(){
        // Méthode 1 : en passant par l'EntityManager
        $queryBuilder = $this->createQueryBuilder('e');
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;
    }

    public function lastEvent($limit){
        $queryBuilder = $this->createQueryBuilder('e')
            ->select('e')
            ->where('e.online = :online')
            ->orderBy('e.createdAt', 'DESC')
            ->setParameter('online', true)
            ->setMaxResults($limit);
        $query = $queryBuilder->getQuery();
        $resultat = $query->getResult();
        return $resultat;
    }

    public function getEvents(){
        $query = $this->createQueryBuilder('e')
            ->select('e')
            ->orderBy('e.createdAt', 'DESC')
            ->getQuery();

       $result = $query ->getResult();

        return $result;
    }


}
