<?php

namespace Meupf\PlateformBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends EntityRepository
{
    public function getGallerys(){
        $query = $this->createQueryBuilder('g')->getQuery();
        //$query ->setFirstResult(($page-1) * $nbPerPage)
        //->setMaxResults($nbPerPage);
        $resultat = $query->getResult();

        return $resultat;
    }


    public function getGalleries(){
        $query = $this->createQueryBuilder('g')
                      ->getQuery();
        $results = $query->getResult();
        return $results;
    }

    public function lastImage($limit){
        $queryBuilder = $this->createQueryBuilder('s')
            ->select('g')
            ->from('MeupfPlateformBundle:Gallery', 'g')
            ->orderBy('g.createdAt', 'DESC')
            ->setMaxResults($limit);
        $query = $queryBuilder->getQuery();
        $resultats = $query->getResult();
        return $resultats;
    }
}
