<?php

namespace Meupf\PlateformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{
    public function getMedias(){
        $query = $this->createQueryBuilder('s')->getQuery();
        //$query ->setFirstResult(($page-1) * $nbPerPage)
            //->setMaxResults($nbPerPage);
        $resultat = $query->getResult();

        return $resultat;
    }
}
