<?php

namespace Meupf\PlateformBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ResponsableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsableRepository extends EntityRepository
{
    public function getResponsables($page, $nbPerPage){
        $query = $this->createQueryBuilder('s')
            // Jointure sur l'attribut image
            ->getQuery();
        // On définit l'annonce à partir de laquelle commencer la liste
        $query ->setFirstResult(($page-1) * $nbPerPage)
            // Ainsi que le nombre d'annonce à afficher sur une page
            ->setMaxResults($nbPerPage);

        // Enfin, on retourne l'objet Paginator correspondant à la requête construite
        // (n'oubliez pas le use correspondant en début de fichier)
        return new Paginator($query, true);
    }

    public function findResponsable($limit){
        $queryBuilder = $this->createQueryBuilder('r')
            ->select('r')
            //->from('MeupfPlateformBundle:Sermon', 'u')
            ->setMaxResults($limit);
        $query = $queryBuilder->getQuery();
        $resultat = $query->getResult();
        return $resultat;
    }

}
