<?php

namespace Meupf\PlateformBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * SliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderRepository extends EntityRepository
{
    public function lastSlider($limit){
        $queryBuilder = $this->createQueryBuilder('s')
            ->select('u')
            ->from('MeupfPlateformBundle:Slider', 'u')
            ->orderBy('u.createdAt', 'DESC')
            //->setParameter('identifier', 100)
            ->setMaxResults($limit);
        $query = $queryBuilder->getQuery();
        $resultats = $query->getResult();
        return $resultats;
    }


    public function getSliders($page, $nbPerPage){
        $query = $this->createQueryBuilder('s')
            ->getQuery();

        // On définit l'annonce à partir de laquelle commencer la liste
        $query ->setFirstResult(($page-1) * $nbPerPage)
            ->setMaxResults($nbPerPage);
        return new Paginator($query, true);
    }
}
